### ISSUE TITLE
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by ashvin-acid** [westmonroe/pdf-puppeteer#33]
I got the following error when long HTML data.
```
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at /home/pct-22/projects/node-api/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (/home/pct-22/projects/node-api/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/pct-22/projects/node-api/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/home/pct-22/projects/node-api/node_modules/puppeteer/lib/helper.js:112:23)
    at Object.convertHTMLToPDF [as default] (/home/pct-22/projects/node-api/node_modules/pdf-puppeteer/src/convertHTMLToPDF.js:22:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'TimeoutError'
}
```

**Comment by yangyang158** [comment]
请问一下 这个问题解决了吗

**Comment by Shaunwild97** [comment]
Same here. Anyways to speed up PDF generation or increase the timeout would be much appreciated.

**Comment by cr7boulos** [comment]
Hi folks, 
There is a PR up here to resolve the issue. Looking to add a unit test to prove out the fix works as expected but this should be merged in soon.
