### ISSUE TITLE
Issue with cURL

### ISSUE THREAD

**Issue by chriskacerguis** [westmonroe/pdf-puppeteer#4]
Hello,

Thanks for such an awesome library (it has saved me a LOT of time).  I've noticed an odd problem...

If I send a simple HTML page using postman everything works great, then I use postman to generate the cURL code

```
curl -X POST \
  http://localhost:3000/api/pdf \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 1a229ea4-8187-47a7-8b65-c30733182e40' \
  -d '<html>
<head>
<title>This is a simple test</title>
</head>
<body>
<p>Hello!</p>
</body>
</html>'
```

And when I run that, I get the following error:

```
Server listening on port 3000(node:18) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:514:11)
    at Request.respond (/usr/src/app/node_modules/puppeteer/lib/NetworkManager.js:450:50)
    at Page.page.once.request (/usr/src/app/src/convertHTMLToPDF.js:25:13)
    at Object.onceWrapper (events.js:273:13)
    at Page.emit (events.js:182:13)
    at NetworkManager.Page._networkManager.on.event (/usr/src/app/node_modules/puppeteer/lib/Page.js:125:74)
    at NetworkManager.emit (events.js:187:15)
    at NetworkManager._handleRequestStart (/usr/src/app/node_modules/puppeteer/lib/NetworkManager.js:247:10)
    at NetworkManager._onRequest (/usr/src/app/node_modules/puppeteer/lib/NetworkManager.js:200:10)
    at NetworkManager._onRequestIntercepted (/usr/src/app/node_modules/puppeteer/lib/NetworkManager.js:177:12)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process witha non-zero exit code.
(node:18) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/usr/src/app/node_modules/puppeteer/lib/NavigatorWatcher.js:74:21)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

and thus, no PDF is generated.  Any ideas what the issue might be?  It's really odd that Postman works fine but the cURL code generated from Postman does not.

Thank you for your time!

Chris

**Comment by chriskacerguis** [comment]
Hello Again,

Ok, the issue is somewhat Postman's fault, in that the data must be posted as raw, but Postman doesn't include the appropriate header in the cURL output.  So, this code works:

```sh
curl -X POST http://localhost:3000/api/pdf \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: text/plain' \
-H 'Postman-Token: 1a229ea4-8187-47a7-8b65-c30733182e40' \
-d '<html>
<head>
<title>This is a simple test</title>
</head>
<body>
<p>Hello!</p>
</body>
</html>'
```

that said, would it be helpful to have some better error handling vs. the error?

**Comment by joehiggs** [comment]
I can take a look this weekend--thanks for reaching out!

**Comment by joehiggs** [comment]
So I took a look at all this and ended up pushing/publishing a few changes. I added a check to make sure the body type is a string. If that check fails, the updated example error handling will catch it. I also updated the postman collection a bit. I realized the one large example was misconfigured, but it is fixed now.
